version: '3'
services:

  db:
    image: postgres:14-alpine
    restart: always 
    command: -p 5432
    env_file:
      - .env 
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

  redis:
    image: redis:7
    container_name: redis
    ports:
      - 6370:6379

  web_server:
    build: .
    command: bash -c "python3 ./test_task/manage.py migrate
      && python3 ./test_task/manage.py loaddata ./test_task/db.json
      && python3 ./test_task/manage.py runserver 0.0.0.0:8000"
    ports: 
      - "8000:8000" 
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env 

volumes:
  pgdbdata: null